spring:
  profiles:
    active: local
---
spring:
  profiles: local
  kafka:
    template: # устанвливаем топик в который будут посылаться сообщения
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer # так как libraryEventId типа Integer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # payload, который посылается это Book, то есть будет сериализован в String
      properties: # override default config values
        acks: all
        retries: 10
    admin: # AdminKafka класс, для создания topic
      properties:
        bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
---
spring:
  profiles: dev # development - для примера, что могут быть разные profile и разные конфигурации для каждого
  kafka:
    producer:
      bootstrap-servers: dev:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
---
spring:
  profiles: prod # production - для примера
  kafka:
    producer:
      bootstrap-servers: prod:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer